FROM ruby:2.4.0

ENV PUPPET_GEM_VERSION="~> 5.0"

WORKDIR /module

COPY Gemfile /bundle/Gemfile
env BUNDLE_GEMFILE=/bundle/Gemfile
RUN bundle install

ENTRYPOINT ["bundle", "exec", "rake"]

CMD ["-T"]
