FROM ruby:2.1.9

ENV PUPPET_GEM_VERSION="~> 4.0"

WORKDIR /module

COPY Gemfile /bundle/Gemfile
env BUNDLE_GEMFILE=/bundle/Gemfile
RUN bundle install

ENTRYPOINT ["bundle", "exec", "rake"]

CMD ["-T"]
